modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "expanded_ecosphere"
version = "${version}"
displayName = "Expanded Ecosphere"
authors = "Cristelknight, William Wythers"
description = '''
In this mod I seek to re-create the vanilla biomes in a way that makes a more realistic and atmospheric world.
'''
logoFile = "pack.png"

[[dependencies.expanded_ecosphere]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expanded_ecosphere]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expanded_ecosphere]]
modId = "cristellib"
mandatory = true
versionRange = "[1.1.5,)"
ordering = "NONE"
side = "BOTH"