modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "Cristelknight, William Wythers"
description = '''${mod_description}'''
logoFile = "pack.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cristellib"
mandatory = true
versionRange = "[${cristellib_version},)"
ordering = "NONE"
side = "BOTH"